import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import Consumer from './Consumer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ejercicio Front</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='titulo'>Ejercicio de Front</h1>
        <div className='card__container'>
          <Consumer />
        </div>
      </main>
    </>
  )
}
